version: "3.9"

services:

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    ports:
      - "9092:9092"
      - "29092:29092"
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --check=false
      - --kafka-addr=INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr=INSIDE://redpanda:29092,OUTSIDE://localhost:9092
    
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=redpanda:29092

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docstream
    volumes:
      - pgdata:/var/lib/postgresql/data

  dbgate:
      image: dbgate/dbgate
      ports:
        - "3001:3000"
      depends_on:
        - postgres
      environment:
        CONNECTIONS: con1
        LABEL_con1: DocStream
        SERVER_con1: postgres
        USER_con1: user
        PASSWORD_con1: password
        PORT_con1: 5432
        ENGINE_con1: postgres@dbgate-plugin-postgres

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  nexus:
    container_name: nexus
    build: ./nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data

  maven-uploader:
    image: maven:3.9.9-eclipse-temurin-21
    volumes:
      - ./services/common-data:/workspace/common-data
      - ./config:/scripts
      - nexus-data:/nexus-data:ro
    entrypoint: ["/bin/bash", "/scripts/upload-common.sh"]

  tesseract-service:
    build:
      context: .
      dockerfile: services/Tesseract/Dockerfile
    container_name: tesseract-service
    volumes:
      - ./testing:/app/images
    ports:
      - "8082:8082"

volumes:
  pgdata:
  grafana-data:
  nexus-data: