server:
  port: 8086

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  kafka:
    consumer:
      group-id: validate-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.docstream.commondata.dto.DocumentProcessingEvent
        spring.json.use.type.headers: false # Omite las cabeceras, entre ellas type, que indica una ruta distinta para DocumentProcessingEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # PostgreSQL datasource configuration
  datasource:
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect

docstream:
  topics:
    input: store-documents

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true